- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: configure and deploy mamebox
  hosts: mamebox
  remote_user: root

  roles:
    - mamebox
